export const SITE_MAP = {
    INDEX: "/",
    AUTH: {
        LOGIN: "login",
        REGISTER: "register",
        FORGOTPASSWORD: "forgot-password",
        RESETPASSWORD: "reset-password/:email"
    },
    ADMIN: "/admin",
    MOD: "/mod",
    USERS: "users",
    ROOMS: "blocks/:id/rooms",
    ROOMS_GENERATION: "blocks/:id/rooms/generate-rooms",
    BLOCKS: "blocks",
    UTILITIES: "utilities",
    TRANSACTIONS: "transactions",
    STATISTICS: "statistics",
    ROOM: "room",
    ROOM_DETAIL: "room/:id",
    RENT: "rental",
    RENT_DETAIL: "rental/:id",
    RENTALS: "rentals",
    MY_RENTAL: "my-rental",
    MY_RENTAL_DETAIL: "my-rental/:id",
    PAYMENTS: "payments",
    MY_PAYMENT: "my-payment",
    MY_PAYMENT_DETAIL: "my-payment/:id",
    MY_CHECKLIST: "/my-checklist",
    MY_PROFILE: "/my-profile",
    MY_STATISTICS: "/my-statistics",
    BECOME_HOST: "/become-host"
}
